### ISSUE TITLE
Handle inability to connect to kafka

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/fluent-bit-kafka-output-plugin#4]
Throw error and continually re-try to connect instead of crashing, which is the current behavior.

**Comment by yenicapotediaz** [comment]
Summary: One of the things I spent doing while on the ticket was to figure out a way to deal with Kafka/zookeeper disconnecting at any given moment, that lead me into all sorts of rabbit holes. While that is outside the scope of this ticket, it is something we should think about and possibly create another separate issue on it. My solution for this issue was to run a time loop in the FLBPluginInit and within it create the Kafka producer, if any errors result it will continue to try and connect until the time runs out. If no connection was established, then it will be able to let the user know without crashing.
